export const confidentiality_politics =
  {
    "": "Bienvenue sur KISSING, l’application de rencontres par affinité. Kissing est une remarquable plateforme vous permettant de faire des rencontres tout en partageant des moments très cool et sympas dans les contextes habituels qui vous vont le mieux. Il suffit de vous inscrire en remplissant des informations sur vous permettant aux autres utilisateurs de vous voir, et ensuite de chatter avec des milliers de célibataires tout près de chez vous selon vos envies et le but que vous vous êtes fixés sur la plateforme.\n" +
      "Notre politique de confidentialité explique comment nous-mêmes et certaines des sociétés avec lesquelles nous travaillons collectons, utilisons, partageons et protégeons les informations dans le cadre de nos services mobiles, web et logiciels fournis en rapport avec les services Kissing (ci-après dénommés collectivement « Application »). Elle présente également vos options concernant la collecte et l’utilisation de vos données personnelles. En utilisant notre Application, vous comprenez et acceptez le fait que nous fournissons une plate-forme pour l’échange de contenus, notamment les chats, photos et autres données sur l’Application et vous acceptez de le partager publiquement. Cela signifie que d’autres personnes qui utilisent l’Application peuvent rechercher, voir, utiliser ou partager ce que vous publiez sur l’Application, conformément aux conditions générales de la présente Politique de confidentialité et à nos conditions d’utilisations.\n" +
      "Notre politique de confidentialité s’applique à l’ensemble des visiteurs, des personnes qui ont recours à l’Application et autres personnes qui accèdent à l’Application",
    "1. INFORMATIONS QUE NOUS RECUEILLONS": "Nous recueillons les types d’informations suivantes. Informations que vous nous fournissez directement :\n" +
      "· votre nom d’utilisateur, votre mot de passe, votre numéro de téléphone ou votre adresse e-mail lorsque vous vous inscrivez pour créer un compte Kissing ;\n" +
      "· les informations que vous nous fournissez pour créer votre profil d’utilisateur (notamment votre nom, votre photo et votre numéro de téléphone). Ces données nous permettent d’aider les Personnes qui utilisent le Service à se rencontrer mutuellement sur Kissing ;\n" +
      "· le Contenu d’utilisateur (photos, tchats et autres supports) que vous publiez sur le Service ;\n" +
      "· les communications entre Kissing et vous-même. Il peut s’agir par exemple d’e-mails de notre part, en rapport avec l’Application. Veuillez noter que vous ne pouvez pas refuser de recevoir ce type de messages.\n" +
      "Faire des rencontres sur Kissing :\n" +
      "· Si vous le désirez, vous pouvez utiliser la fonctionnalité Rechercher pour trouver d’autres personnes possédant un compte Kissing, par le biais (i) de vos connaissances quelconques, (ii) de sites de réseaux sociaux tiers.\n" +
      "· Si vous choisissez de rechercher par le biais d’un (ii) site de réseau social tiers, vous êtes invité(e) à créer un lien vers ce service tiers et vous acceptez que toute information que ce service peut nous fournir soit régie par la présente Politique de confidentialité.\n" +
      "· Remarque sur la fonctionnalité Invitez vos amis : si vous choisissez d’inviter une personne sur le Service en utilisant la fonctionnalité Invitez vos amis, vous pouvez sélectionner cette personne directement dans vos contacts sur votre appareil et lui envoyer un texto ou un e-mail depuis votre compte personnel. Vous comprenez et acceptez le fait que vous êtes responsable des éventuels frais qui s’appliquent aux communications envoyées depuis votre appareil. Comme ce type d’invitation provient directement de votre compte personnel, Kissing n’a pas accès à ces communications et ne les contrôle pas.",
    "2. UTILISATION DE VOS DONNÉES PERSONNELLES": "En plus des cas d’utilisation spécifiques décrits dans la présente Politique de confidentialité, il est possible que nous utilisions les données que nous recevons aux fins suivantes :\n " +
      "· vous aidez à accéder efficacement à vos données personnelles après votre connexion ;\n" +
      "· mémoriser vos données personnelles pour vous éviter d’avoir à les saisir de nouveau pendant votre visite ou à l’occasion de vos prochaines visites sur l’Application ;\n" +
      "· vous fournir, à vous et à des tiers, du contenu et des informations personnalisées, pouvant inclure des publicités en ligne et autres formes de marketing ;\n" +
      "· assurer, améliorer, tester et contrôler l’efficacité de notre Application ;\n" +
      "· développer et tester de nouveaux produits et fonctionnalités ;\n" +
      "· surveiller différents indicateurs (notamment sur le nombre total de visiteurs, la fréquentation et des schémas démographiques) ;\n" +
      "· diagnostiquer ou résoudre des problèmes techniques ;\n" +
      "· automatiquement mettre à jour Kissing sur votre appareil.",
    "3. PARTAGE DE VOS DONNÉES PERSONNELLES": "Nous nous engageons à ne pas louer ni vendre vos données personnelles à des tiers externes à Kissing (ou au groupe de sociétés dont Kissing fait partie) sans votre consentement, sauf disposition contraire énoncée dans la présente Politique.\n" +
      "Tiers avec lesquels nous pouvons partager vos données personnelles  \n" +
      "· Nous pourrons partager votre Contenu d’utilisateur et vos données personnelles (y compris, mais sans s’y limiter, des données d’utilisation) avec des entreprises qui font légalement partie du même groupe de sociétés que Kissing ou qui rejoignent ce groupe (les « Filiales »). Les Filiales peuvent utiliser ces données pour contribuer à fournir, comprendre et améliorer l’Application (notamment en fournissant des analyses) et leurs propres services (par exemple en vous offrant une expérience enrichie et plus pertinente). Les Filiales doivent toutefois respecter vos choix concernant les personnes autorisées à voir vos informations personnelles.\n" +
      "· Nous pourrons également partager vos données personnelles, ainsi que des informations avec des organisations tierces (les « Prestataires de services ») afin de vous fournir l’Application. Nos Prestataires de services auront accès à vos données personnelles selon ce qui est raisonnablement nécessaire pour vous fournir l’Application dans le respect des conditions de confidentialité raisonnables.\n" +
      "· Nous pourrons supprimer certaines données qui permettent de vous identifier et partager des données rendues anonymes avec d’autres parties. Nous pourrons aussi combiner certaines données avec d’autres afin qu’elles ne puissent plus être associées à vous, et partager ces données agrégées.\n" +
      "Tiers avec lesquels vous pouvez choisir de partager votre Contenu d’utilisateur :\n" +
      "· Toute information ou tout contenu (Contenu d’utilisateur ou autre) que vous divulguez volontairement en vue d’une publication sur l’Application devient disponible pour le public et est soumis aux paramètres de confidentialité applicables que vous avez définis. Pour modifier vos paramètres de confidentialité sur l’Application, vous devez modifier vos paramètres de profil. Une fois que vous avez partagé votre Contenu d’utilisateur ou que vous l’avez rendu public, il peut être à nouveau partagé par d’autres.\n" +
      "· En fonction de vos paramètres de confidentialité et de profil, tout Contenu d’utilisateur que vous rendez public peut faire l’objet de recherches par d’autres personnes et peut être utilisé par l’API Kissing. L’utilisation de l’API Kissing est soumise aux Conditions d’utilisation de l’API qui intègrent les conditions de la présente Politique de confidentialité.\n" +
      "· Si vous supprimez des informations que vous avez publiées sur l’Application, leurs copies peuvent rester visibles, soit dans les pages archivées et mises en cache de l’Application, soit si d’autres Personnes qui utilisent l’Application ou tierces parties utilisant l’API Kissing les ont copiées ou enregistrées.\n" +
      "Scénario en cas de changement de propriétaire :· Si nous vendons ou transférons de quelque manière que ce soit Kissing ou nos actifs, en tout ou partie (par exemple, dans le cadre d’une fusion, d’une acquisition, d’une faillite, d’une dissolution ou d’une liquidation) à une autre organisation, vos données personnelles (notamment votre nom, votre adresse e-mail, votre Contenu d’utilisateur et toute autre information collectée par le biais du Service) pourront faire partie des éléments vendus ou transférés. Vous continuerez néanmoins à être propriétaire de votre Contenu d’utilisateur. L’acheteur ou le bénéficiaire du transfert devra alors respecter les engagements que nous avons pris dans le cadre de la présente Politique de confidentialité.\n" +
      "Réponse à des requêtes judiciaires et prévention de tout risque de dommage :\n" +
      "· Nous pourrons accéder à vos données personnelles, les conserver et les partager en réponse à une demande légale (mandat de perquisition, ordonnance d’un tribunal ou autre) si nous pensons en toute bonne foi que la loi nous y oblige. Cela peut inclure la réponse à des demandes légales provenant de juridictions en dehors du Cameroun, lorsque nous avons toutes les raisons de penser que la réponse est requise par la loi de cette juridiction, qu’elle s’applique aux Personnes qui utilisent l’Application et qui dépendent de cette juridiction et qu’elle est conforme aux normes internationalement reconnues. Nous pouvons également accéder à vos informations, les conserver et les communiquer quand nous estimons qu’elles sont nécessaires pour détecter et empêcher la fraude ou toute autre activité illicite, pour protéger vos intérêts, les nôtres ou ceux d’autrui, et pour prévenir tout préjudice corporel imminent. Nous pourrons accéder à vos données personnelles, les traiter et les conserver pendant une période prolongée dans le but de répondre à une requête judiciaire, à une enquête gouvernementale ou à une enquête concernant la possible violation de nos conditions ou politiques, ou en vue d’empêcher tout dommage.",
    "4. VOS CHOIX CONCERNANT VOS DONNÉES PERSONNELLES": "Informations sur votre compte et paramètres de profil/confidentialité \n" +
      "· Vous pouvez mettre votre compte à jour à tout moment en vous connectant et en modifiant les paramètres de votre profil.\n" +
      "· Pour ne plus recevoir d’e-mails de notre part, il vous suffit de cliquer sur le lien de désabonnement inclus dans chacun des messages. Comme indiqué plus haut, vous ne pouvez pas refuser les communications en rapport avec le Service (vérification du compte, confirmations et rappels concernant les achats et la facturation, changements et mises à jour des fonctionnalités du Service, avis techniques et de sécurité, etc.).\n" +
      "Durée de conservation de votre Contenu d’utilisateur :\n" +
      "· Après la résiliation ou la désactivation de votre compte, Kissing, ses Filiales ou ses Prestataires de services pourront conserver certaines données (y compris les informations de votre profil) et votre Contenu d’utilisateur pendant une durée raisonnable commercialement parlant, à des fins de sauvegarde, d’archivage ou d’audit.\n",
    "5. AUTRES SITES WEB ET APPLICATIONS": "Nous ne sommes pas responsables des pratiques employées par les sites web et services liés à notre Application ou provenant de notre Service, y compris des informations et du contenu qu’ils renferment. Veuillez garder à l’esprit que notre Politique de confidentialité ne s’applique pas aux autres sites web et  applications de tiers auxquels vous accédez depuis des liens figurant sur notre Application. ",
    "6. MODIFICATIONS DE LA POLITIQUE DE CONFIDENTIALITÉ": "Kissing se réserve le droit de modifier ou de mettre à jour de temps à autre la présente Politique de confidentialité. Veuillez donc à la consulter régulièrement. Selon les circonstances, nous pourrons vous avertir de modifications et mises à jour par d’autres moyens. En continuant à utiliser Kissing ou le Service après toute modification de la présente Politique de confidentialité, vous signifiez votre acceptation de ces modifications.",
  };

export const signal_problems = {
    "" : 'Les problèmes présents sur la plateforme Kissing peuvent être d’origine diverses en fonction des situations vécues par chaque utilisateur:',
    '  1. Signaler le décès d’une personne qui utilise l’Application': 'En cas de décès d’une personne qui utilise Kissing, contactez-nous. Dans une telle situation, nous communiquons généralement par e-mail. Si nous avons besoin de renseignements supplémentaires, nous vous contacterons donc à l’adresse e-mail indiquée dans votre demande',
    '  2. Signaler des activités qui vont à l’encontre de notre politique': 'Des activités telles l’utilisation des faux profils profils, harcèlement ou meme de spam sont totalement proscrites et vont à l’encontre de notre politique. En cas de remarque de ces activités, contactez-nous. Nous analyserons les différentes situations et prendrons des décisions adéquates dans l’optique de stopper ou réparer le tord si celui-ci à été commis.',
    '  3. Signaler un problème lié à votre compte': 'Si vous avez des disfonctionnements ou des problèmes à votre compte, contactez-nous. Nous les recevrons, les analyserons puis vous enverrons un retour afin que vous soyez éclairés par rapport au problème en vue de trouver des solutions.',
    '  4. Comment nous contacter afin de vous aider?': 'Nous sommes disponibles et répondons à toutes vos questions et préoccupations via notre page d’aide en cliquant sur contactez-nous'
}

export const security = {
    "": "Votre sécurité est ce qu’il y’a de plus chère à nos yeux et c’est dans cet optique que nous avons évaluer des situations qui pourraient troubler  votre tranquillité et par dessus tout votre sécurité",
    "  1. Renforcer la sécurité de votre compte": "Un compte mal sécurisé est vulnérable et s’expose à des attaques extérieures mais aussi à des oublis et confusions personneles. Donc il est primordial de maximiser la sécurité de votre compte en variant les termes de ceux-ci(ne pas mettre des codes ou combinaisons comme 123, abc, 000 etc...) Mais en y ajoutant des caractères spéciaux ou en évitant de divulguer vos informations de connexion à des tiers, vous éviterez bien de mauvaises surprises à cet égard.",
    "  2. La diffusion de vos informations ou images intimes sans votre consentement": "Dès lors que vous décidez de vous inscrire sur la plateforme Kissing, vous avez au moins 18ans donc de ce fait majeur. Il est donc important de savoir limiter certaines conversations et éviter d’envoyer vos informations ou images intimes personnelles de peur que certains individus de mauvaises moralités en font mauvais usage. Soyez prudent et n’oubliez pas que votre intimité est précieuse.\n",
    "  3. L’intimidation et le harcèlement":"Ces deux termes font partie des sujets délicats et des préoccupations actuelles que font face plusieurs utilisateurs sur la toile. Nous nous efforçons de faire respecter la loi contre des contenus tendant à promouvoir ces genres de pratique. C’est pour cela qu’il est important voir  essentiel, voir primordial de ne pas céder ou se laisser faire face à cela, car nous continuons d’actualiser et de réviser nos politiques à l’aide de spécialistes pour continuer à lutter contre ces fléaux",
    "  4. Sécurité de vos données utilisateur":"Nous nous engageons à ne pas louer ni vendre vos données personnelles à des tiers externes à Kissing (ou au groupe de sociétés dont Kissing fait partie) sans votre consentement, sauf disposition contraire énoncée dans la présente Politique. De ce fait, soyez rassuré de la protection de vos données utilisateurs car si nous les avons en notre possession, c’est pour faire valoir de plein droit votre statut en tant que membre de la communauté Kissing."
}
