/* eslint-disable prettier/prettier */
const icons = {
	back: 'chevron-left',
	next: 'chevron-right',
	lock: 'lock-outline',
	eye: 'eye-outline',
	eyeOff: 'eye-off-outline',
	boy: 'human-male',
	girl: 'human-female',
	uncheck: 'checkbox-blank-circle-outline',
	check: 'checkbox-blank-circle',
	simpleCheck: 'check',
	account: 'account-outline',
	email: 'email-outline',
	erase: 'backspace-outline',
	message: 'android-messages',
	addCircle: 'plus-circle-outline',
	dropdown: 'chevron-down',
	delete: 'delete',
	menu: 'menu',
	filter: 'filter-menu-outline',
	love: 'heart-outline',
	subscription: 'diamond-stone',
	chat: 'chat-outline',
	notifications: 'bell-ring-outline',
	close: 'close',
	settings: 'cog-outline',
	edit: 'account-edit-outline',
	blocked_user: 'account-cancel-outline',
	law: 'scale-unbalanced',
	warning: 'shield-alert-outline',
	security: 'shield-check-outline',
	share: 'share-variant-outline',
	logout: 'logout',
	star: 'star',
	star_outline: 'star-outline',
	info: 'information-outline',
	pencil: 'pencil',
	sendMessage: 'near-me',
	picture: 'camera',
	upload: 'upload',
	plus: 'plus',
	refresh: 'refresh'
};

export default icons;
